language: ruby
rvm:
- 2.2.2
script:
- bundle install
- bundle exec jekyll build
after_success:
- git clone https://$GITHUB_REPO
- cd $(basename ${GITHUB_REPO%.git})
- git config --global user.name "Travis CI"
- git config --global user.email ${AUTHOR_EMAIL}
- rsync -az --delete --exclude '.git*' ../_site/ .
- touch .nojekyll
- git add -A .
- git commit -m "Generated Jekyll site by Travis CI - ${TRAVIS_BUILD_NUMBER}"
- git push "https://${DEPLOY_KEY}@${GITHUB_REPO}" origin ${REPO_TARGET_BRANCH}
branches:
  only:
  - source
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
  - GITHUB_REPO: github.com/amlinger/amlinger.github.io.git
  - REPO_TARGET_BRANCH: master
  - AUTHOR_EMAIL: anton.amlinger@gmail.com
  - secure: jUXrcEq3zuNxj3YK7XqLD21IxZUmx4MfH/wcmpTnu1/qmKH16FR+nGHHVIykAHK3QpaT5qwUHZBkQ3vTs6uXVFqCCXWyYq1EW2fD17qcPYaRWGz7Ujb+jRSbhiRR2D4DJEeddYhOXEgIvpTkKTEnYQ0ufoJjN431GBnq8zR7sKv9/j0c0F3LTS4AHhl6W2KP04YmsmnPyzdZawW03jTTUPnW/s3Q1MjfrgyAbeBULz08FMUySyCoy5u05y6rYX3RQvp871RXqorhTg1PnDkP3DP9S6BCXR8CHJbh6ssx71rBMoETkkmbucUPdHhD7Yi0fBfsrMSD7+FH1YgfbyL8Bme+0jl1zW8A4HN4PsuBFunknU2xMdos7XDjBIbyoOhz6dOWvct3izxw+eT9Z58n+fQTId5NzYAh9PoKv+bSUGjpxmgebh5s4eJ7FXxzznBQoo1urr8gJP+zOGTmu63n3LfG+zMoty61tEY/kziA65WqUFIkECX2UPI272ub97fZ04swGRkZtGErstzVdGKFwmIW6L4wiVO8XOUS4qc0yNVrcnYaAGj+assNFjH0bW4MMCAjN5lgtj1yuxlTgxAZN5JGpsLJhqYQNelh+yWJraO8aY8z49rZOCJRbjajlMeSqYd2CEPg+txow0r1yMxInz7ed8N1J1vn5my5JnVXvME=
