language: ruby
rvm:
- 2.2.2
script:
- bundle install
- bundle exec jekyll build
after_success:
- git clone https://$GITHUB_REPO
- cd $(basename ${GITHUB_REPO%.git})
- git config --global user.name "Travis CI"
- git config --global user.email ${AUTHOR_EMAIL}
- rsync -az --delete --exclude '.git*' ../_site/ .
- touch .nojekyll
- git add -A .
- git commit -m "Generated Jekyll site by Travis CI - ${TRAVIS_BUILD_NUMBER}"
- git push "https://${DEPLOY_KEY}@${GITHUB_REPO}" HEAD:${REPO_TARGET_BRANCH}
branches:
  only:
  - source
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
  - GITHUB_REPO: github.com/amlinger/amlinger.github.io.git
  - REPO_TARGET_BRANCH: master
  - AUTHOR_EMAIL: anton.amlinger@gmail.com
  - DEPLOY_KEY:
    - secure: Wmez7FyBr5Y5mRNN/3GbBJSOAwIlbwfDiOJ3p9KzyL9Yb3n6KlNJFwTwKpzPehCeFMPoiihuiQP2MLd/9MURVEHCtP35lYBCheLSIUmkgIJfAOFAc4vYBvUre6omAf4TjLVFH7nzdf2Rdqbc6fNhcxQsjS+lRFsVueTbiMOefn1y/nqQxJw9tZCvDWw+oAVG2zud8IcQmlYWmlNSkmnmKnwS/nc2sNXSgpNkEwoLmjpzYRJVADjIOtwxl+kxnjfNO25zozLge4v8nc2fcbzdnaBk1mjOZyXjnHh1ufBgDxRHmIicJa0U/4HPRfSo38HkGWBVPiD7hhHRfX5BwFVwVl8ubqlL0oEvLDwLs1NUTMp5/xZHXAEylIvoygZaRExSgAui2wIZdi0Q5sJsTNZKbl098grKZQcJxt7O/fx8Eu1eIzQIbVxtbU6P29+r5prJk5RWHmlf875kYqbhjklP0ytA3guMBaL+zX/o1X/jHrcrDzfKMglLIQu8vGaMlOy8/rjKyEvy3cbj7GvJz8eVjDKA78gwH2MJ8tdoWlQUomgKRehmtmqG5E12McW7Ab5yPw6MLgVwfFISBMvf/RT9Qse55q7A96zquLg4aPr/AY9r/h5/6HK9xUYGr9zjGgWvKaryH3xcdpTgH24HmmZ8NPduOSgE2sKbBwOxR53Fn/E=
