# We tell Travis to run in a Ruby 2.3 environment
#
# The main idea behind this is to clone the existing Git repository in our
# current working folder after a build has succeeded, and jump into the
# repository folder. There, we copy over the generated files, commit the result,
# and force push the result back to the master branch.
language: ruby
rvm:
- 2.3

script:
  - bundle exec jekyll build

# after building, copy the site into the master branch and push back to Github
after_success:
  - git clone https://$GITHUB_REPO
  - cd $(basename ${GITHUB_REPO%.git})
  - git config user.name "Travis CI"
  - git config user.email ${EMAIL}
  - rsync -az --delete --exclude '.git*' ../_site/ .
  - touch .nojekyll
  - git add -A .
  - git commit -m "Generated Jekyll site by Travis CI - ${TRAVIS_BUILD_NUMBER}"
  - git push --force "https://${DEPLOY_KEY}@${GITHUB_REPO}" HEAD:${REPO_TARGET_BRANCH}

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
  - GITHUB_REPO: github.com/amlinger/amlinger.github.io.git
  - REPO_TARGET_BRANCH: master
