# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
safe:        false
title: Anton Amlinger
email: antonamlinger@gmail.com
description: >
  Anton Amlinger
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://blog.amlinger.me" # the base hostname & protocol for your site

firstname: Anton
lastname: Amlinger

github_username:  amlinger
twitter_username: antonamlinger
linkedin_username: anton-amlinger-8347a577

# Markdown parse settings
markdown: kramdown

kramdown:
  input: GFM

#
highlighter: pygments.rb
tags:
  highlight:
    linenos: true

whitelist:
  - to_gravatar

gems:
  - jekyll-gist

#gems:
#  - liquid-md5
