# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# SITE SETTINGS ===============================================================
safe:        false
title: Anton Amlinger
email: antonamlinger@gmail.com
description: >
  Anton Amlinger
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://blog.amlinger.me" # the base hostname & protocol for your site

firstname: Anton
lastname: Amlinger

github_username:  amlinger
twitter_username: antonamlinger
linkedin_username: anton-amlinger-8347a577
# END OF SITE SETTINGS ========================================================

# Markdown parse settings
markdown: kramdown

kramdown:
  input: GFM

# Files excluded from being copied to the site folder:
exclude:
  # Travis does not like vendor gems, as they might contain date-errored files:
  # https://github.com/jekyll/jekyll/issues/2938
  - vendor
  - README.md
  - Gemfile
  - Gemfile.lock
  - Guardfile

# Specifies the assets build by jekyll-assets, using Sprockets. More
# comprehensive documentation about what can be found at
# https://github.com/jekyll/jekyll-assets/blob/master/README.md
assets:
  sources:
    - _assets/css

highlighter: pygments.rb
tags:
  highlight:
    linenos: true

whitelist:
  - to_gravatar

# Gems used in this
gems:
  - jekyll-gist
  - jekyll-assets
